apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- namespace.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- postgres-statefulset.yaml
- backendconfig.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
- job.yaml

  # - name: gcr.io/PROJECT_ID/todo-server
  #   newName: gcr.io/dwk-gke-484423/todo-server
images:
- name: PROJECT/IMAGE
  newName: typescriptlover/the_project
  newTag: 75be201d6c9e8f1951e46c17fb4ac7afa981aa89
