apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-project-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kristianka/DevOpsWithKubernetes
    targetRevision: HEAD # Uses tags for production
    path: the_project/manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: project-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
