apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-dep
spec:
  template:
    spec:
      containers:
        - name: todo-server
          env:
            - name: POSTGRES_HOST
              value: "prod-postgres-stset-0.prod-postgres-svc"
